### ISSUE TITLE
Support `CHROME_BIN` to allow npm-based-projects.

### ISSUE THREAD

**Issue by captn3m0** [schliflo/docker-puppeteer#6]
For any project that uses `npm` (not yarn), the `node_modules` path difference makes it unusable easily. Till recently, I was using the following approach in my Dockerfile:

```Dockerfile
ENV CHROME_REVISION=674921
# Ensure that the chromium path hasn't changed (this fails the build early)
RUN ls "/usr/local/share/.config/yarn/global/node_modules/puppeteer/.local-chromium/linux-$CHROME_REVISION/chrome-linux/chrome"
ENV CHROME_BIN="/usr/local/share/.config/yarn/global/node_modules/puppeteer/.local-chromium/linux-$CHROME_REVISION/chrome-linux/chrome"
ENTRYPOINT ["/usr/local/bin/node", "server.js"]
```

However, this requires ugly updates to CHROME_REVISION every release. I attempted to dynamically set the CHROME_REVISION:

```Dockerfile
RUN export CHROME_REVISION=$(node -e "console.log(require('/usr/local/share/.config/yarn/global/node_modules/puppeteer/package.json')['puppeteer']['chromium_revision'])")
```
but docker doesn't support dynamically setting environment variables inside the Dockerfile: https://github.com/moby/moby/issues/29110

So, my current approach is having to write a initscript instead:

```sh
#!/bin/sh
export CHROME_REVISION=$(node -e "console.log(require('/usr/local/share/.config/yarn/global/node_modules/puppeteer/package.json')['puppeteer']['chromium_revision'])")
export CHROME_BIN="/usr/local/share/.config/yarn/global/node_modules/puppeteer/.local-chromium/linux-$CHROME_REVISION/chrome-linux/chrome"
env
ls -lah $CHROME_BIN
echo $CHROME_BIN
/usr/local/bin/node server.js $@
```

I think the simple Dockerfile approach makes more sense here (as the upstream):

```Dockerfile
ENV CHROME_REVISION=674921
ENV CHROME_BIN="/usr/local/share/.config/yarn/global/node_modules/puppeteer/.local-chromium/linux-$CHROME_REVISION/chrome-linux/chrome"
```

but then you'll be stuck with checking the chrome revision every release. (Easiest way is to visit `https://raw.githubusercontent.com/puppeteer/puppeteer/v3.0.1/package.json`).

**Comment by schliflo** [comment]
Thank you for opening the issue. I am not quite sure I fully understand your problem.
So basically you need the path to the Chrome binary. This is tricky to do, as it changes based on the puppeteer release.
What I don't get is what role `yarn` vs. `npm` plays in that. Is it because the binary is in a different directory than it would be when installed through npm? Maybe we could fix this with a symlink then.
I'd be happy to include the export commands of your script in the `RUN` command of the Dockerfile, so you could count on `CHROME_REVISION` and `CHROME_BIN` being correctly set on each build.

> I think the simple Dockerfile approach makes more sense here (as the upstream):

What do you mean with "upstream" here? alekzonder/docker-puppeteer seems largely unmaintained and the approach mentioned is also flawed as it would require me to change `CHROME_REVISION` manually on every release...

Anyways, thanks for bringing the issue up - I hope you can clarify some of my points. With your help I'm sure we can find a solution for this ;)

**Comment by captn3m0** [comment]
>What I don't get is what role yarn vs. npm plays in that

Took me a while to figure this out, but yarn installs puppeteer to `/usr/local/share/.config/yarn/global/node_modules/puppeteer`.

On the downstream side, I'm installing `puppeteer-core` in my local-package dependency:  https://github.com/captn3m0/prometheus-act-exporter/blob/4e18ffa3aba90c701c16627e5cd0cc61e2941c3d/package.json#L27

With that in place, the local `puppeteer-core` searches for a valid puppeteer installation (and doesn't find any.

I attempted to fix this by running this in the Dockerfile:

```Dockerfile
RUN npm config set prefix /usr/local/share/.config/yarn/global/
```

But that didn't work. Maybe I should have tried a bit harder on this path, but this isn't well documented. A symlink from `/usr/local/share/.config/yarn/global/` to `/usr/local/node_modules` to `/usr/local/share/.config/yarn/global/node_modules` maybe?

>I'd be happy to include the export commands of your script in the RUN command of the Dockerfile, so you could count on CHROME_REVISION and CHROME_BIN being correctly set on each build.

This doesn't work, because the variables aren't really exported via RUN. Each bash script invocation is individual and contained, like a subshell, and the environment isn't shared/passed. You have to create a wrapper script which I don't think is feasible for a base image (your repo).

>What do you mean with "upstream" here?

`schliflo/docker-puppeteer` :)

>and the approach mentioned is also flawed as it would require me to change CHROME_REVISION manually on every release...

Don't think there is any other approach that works for base images, since you cannot dynamically set a environment variable without passing it from the docker host system (via a build arg). (See [this example](https://github.com/tensorflow/ecosystem/blob/1b3a0529bfa7e8eca6419cb5bef4d6f85b86c81e/docker/Dockerfile.hdfs#L24) from Tensorflow for eg, and the [moby issue](https://github.com/moby/moby/issues/29110)).

**Comment by schliflo** [comment]
@captn3m0 I just released some work I did on how the Dockerfile is generated. I hope this solves your problem :)
See https://github.com/schliflo/docker-puppeteer/pull/7 for details and please report here if the changes work.

**Comment by captn3m0** [comment]
They don't work :(

```
docker run --entrypoint /usr/bin/env schliflo/docker-puppeteer
PATH=/tools:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
HOSTNAME=ee7dbbfb5db7
NODE_VERSION=12.16.2
YARN_VERSION=1.22.4
APPLICATION_USER=pptruser
APPLICATION_GROUP=pptruser
NODE_PATH=/usr/local/share/.config/yarn/global/node_modules:
LANG=C.UTF-8
CHROME_BIN=/usr/local/share/.config/yarn/global/node_modules/puppeteer/.local-chromium/linux-/chrome-linux/chrome
PPTR_VERSION=
HOME=/home/pptruser
```

**Comment by schliflo** [comment]
Sorry, didn't test ist enough...
The latest commit should fix it:

```bash
PATH=/tools:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
HOSTNAME=a1f10f6af0e7
NODE_VERSION=12.16.2
YARN_VERSION=1.22.4
APPLICATION_USER=pptruser
APPLICATION_GROUP=pptruser
NODE_PATH=/usr/local/share/.config/yarn/global/node_modules:
LANG=C.UTF-8
PPTR_VERSION=3.0.1
CHROME_REVISION=737027
CHROME_BIN=/usr/local/share/.config/yarn/global/node_modules/puppeteer/.local-chromium/linux-737027/chrome-linux/chrome
HOME=/home/pptruser
```

**Comment by captn3m0** [comment]
I'm still getting a incorrect `CHROME_BIN`:

````
docker pull schliflo/docker-puppeteer:latest
latest: Pulling from schliflo/docker-puppeteer
Digest: sha256:5e705f7a2b8e7afbefc4386b5d8f5889d5a4fdbf3d33e9b89c454e0ae03cbdb6
Status: Image is up to date for schliflo/docker-puppeteer:latest
docker.io/schliflo/docker-puppeteer:latest

docker run --entrypoint /usr/bin/env schliflo/docker-puppeteer
PATH=/tools:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
HOSTNAME=ff411ddcdc3b
NODE_VERSION=12.16.2
YARN_VERSION=1.22.4
APPLICATION_USER=pptruser
APPLICATION_GROUP=pptruser
NODE_PATH=/usr/local/share/.config/yarn/global/node_modules:
LANG=C.UTF-8
PPTR_VERSION=3.0.1
CHROME_REVISION=737027
CHROME_BIN=/usr/local/share/.config/yarn/global/node_modules/puppeteer/.local-chromium/linux-/chrome-linux/chrome
HOME=/home/pptruser
```

**Comment by schliflo** [comment]
TIL: You cannot apply the ENV var in the same block as you define it in.
It's fixed now.
```
 flo@mbp  ~/schliflo/docker-puppeteer   master  docker image pull schliflo/docker-puppeteer:latest            
latest: Pulling from schliflo/docker-puppeteer
Digest: sha256:d462b57883c6b9143f59f9e9dba694b22a4ed5afab1383b4b7cfec56cd4a87a0
Status: Image is up to date for schliflo/docker-puppeteer:latest
docker.io/schliflo/docker-puppeteer:latest
 flo@mbp  ~/schliflo/docker-puppeteer   master  docker run --entrypoint /usr/bin/env schliflo/docker-puppeteer:latest
PATH=/tools:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
HOSTNAME=1e79283da87b
NODE_VERSION=12.16.2
YARN_VERSION=1.22.4
APPLICATION_USER=pptruser
APPLICATION_GROUP=pptruser
NODE_PATH=/usr/local/share/.config/yarn/global/node_modules:
LANG=C.UTF-8
PPTR_VERSION=3.0.1
CHROME_REVISION=737027
CHROME_BIN=/usr/local/share/.config/yarn/global/node_modules/puppeteer/.local-chromium/linux-737027/chrome-linux/chrome
HOME=/home/pptruser
```
I'll leave this open this time until you report success :)
Thanks for sticking with me.

**Comment by captn3m0** [comment]
Reporting success :1st_place_medal: 

Thanks a lot! I can now have one-click-upgrades on my repo!

Waiting for the next release :100:

**Comment by schliflo** [comment]
The changes implemented for this issue also enabled me to get automated PRs for pupeteer updates: https://github.com/schliflo/docker-puppeteer/pull/8 🚀🔥
